export const interestsData = [
    { id: 1, name: 'Animes', type: 'interest', colorName: 'blueT2', highlightColor: 'pinkT4', ringColor: 'redT3', ringThickness: "2", },
    { id: 2, name: 'Jogos', type: 'interest', colorName: 'redT2', highlightColor: 'blueT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 3, name: 'Noturno', type: 'interest', colorName: 'altPurpleT4', highlightColor: 'greenT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 4, name: 'Música', type: 'interest', colorName: 'orangeT2', highlightColor: 'redT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 5, name: 'Filmes', type: 'interest', colorName: 'greenT2', highlightColor: 'orangeT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 6, name: 'Viagens', type: 'interest', colorName: 'yellowT2', highlightColor: 'yellowT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 7, name: 'Esportes', type: 'interest', colorName: 'redT3', highlightColor: 'purpleT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 8, name: 'Literatura', type: 'interest', colorName: 'orangeT2', highlightColor: 'altPurpleT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 9, name: 'Arte', type: 'interest', colorName: 'orangeT3', highlightColor: 'pinkT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 10, name: 'Culinária', type: 'interest', colorName: 'yellowT1', highlightColor: 'blueT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 11, name: 'Fitness', type: 'interest', colorName: 'greenT1', highlightColor: 'greenT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 12, name: 'Tecnologia', type: 'interest', colorName: 'blueT3', highlightColor: 'redT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 13, name: 'Fotografia', type: 'interest', colorName: 'orangeT2', highlightColor: 'orangeT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 14, name: 'Moda', type: 'interest', colorName: 'pinkT4', highlightColor: 'yellowT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 15, name: 'Aventura', type: 'interest', colorName: 'yellowT2', highlightColor: 'purpleT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 16, name: 'Sustentabilidade', type: 'interest', colorName: 'greenT2', highlightColor: 'altPurpleT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 17, name: 'DIY', type: 'interest', colorName: 'pinkT2', highlightColor: 'redT4', ringColor: 'transparent', ringThickness: "0", },
    { id: 18, name: 'Ciência', type: 'interest', colorName: 'blueT2', highlightColor: 'blueT3', ringColor: 'transparent', ringThickness: "0", },
];