export const tagsData = [
    { id: 1, name: '+18', type: 'tag', colorName: 'blackT1', highlightColor: 'blackT2', ringColor: 'redT3', ringThickness: "2", weight: "bold" },
    { id: 2, name: 'LOUCURA', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 3, name: 'Baile', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 4, name: 'Solteirões', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 5, name: 'Nerd', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 6, name: 'Temática', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 7, name: 'Universitário', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 8, name: 'Música ao vivo', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 9, name: 'Zero álcool', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 10, name: 'Álcool', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 11, name: 'Na rua', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 12, name: 'Evento', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 13, name: 'Chácara', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 14, name: 'Churrasco', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 15, name: 'Open food', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 16, name: 'Open bar', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 17, name: 'Pop', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 18, name: 'Rock', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 19, name: 'Funk', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 20, name: 'Trap', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 21, name: 'Pagode', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 22, name: 'Light', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 23, name: 'Jogos', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 24, name: 'DJ', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 25, name: 'Atrações', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 26, name: 'Bar', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 27, name: 'Consumíveis', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 28, name: 'Narguilé', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 29, name: 'Área aberta', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 30, name: 'Terraço', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 31, name: 'Piscina', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 32, name: 'Show', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 33, name: 'REVOADA', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 34, name: 'Praia', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 35, name: 'Pista de dança', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 36, name: 'Aniversário', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
];
