export const tagsData = [
    { id: 1, name: 'Universitário', type: 'tag', colorName: '', highlightColor: '' },
    { id: 2, name: 'Baile', type: 'tag', colorName: '', highlightColor: '' },
    { id: 3, name: 'Solteirões', type: 'tag', colorName: '', highlightColor: '' },
    { id: 4, name: 'Nerd', type: 'tag', colorName: '', highlightColor: '' },
    { id: 5, name: 'Temática', type: 'tag', colorName: '', highlightColor: '' },
    { id: 6, name: 'Jogos', type: 'tag', colorName: '', highlightColor: '' },
    { id: 7, name: 'Música Ao Vivo', type: 'tag', colorName: '', highlightColor: '' },
    { id: 8, name: 'Zero álcool', type: 'tag', colorName: '', highlightColor: '' },
    { id: 9, name: 'LOUCURA', type: 'tag', colorName: '', highlightColor: '' },
    { id: 10, name: 'Na rua', type: 'tag', colorName: '', highlightColor: '' },
    { id: 11, name: 'Evento', type: 'tag', colorName: '', highlightColor: '' },
    { id: 12, name: 'Chácara', type: 'tag', colorName: '', highlightColor: '' },
    { id: 13, name: 'Colegial', type: 'tag', colorName: '', highlightColor: '' },
    { id: 14, name: 'Standup', type: 'tag', colorName: '', highlightColor: '' },
    { id: 15, name: 'Sustentável', type: 'tag', colorName: '', highlightColor: '' },
    { id: 16, name: 'Pop', type: 'tag', colorName: '', highlightColor: '' },
    { id: 17, name: 'Rock', type: 'tag', colorName: '', highlightColor: '' },
    { id: 18, name: 'Música ao vivo', type: 'tag', colorName: '', highlightColor: '' },
];
