export const tagsData = [
    { id: 1, name: '+18', type: 'tag', colorName: 'blackT1', highlightColor: 'blackT2', ringColor: 'redT3', ringThickness: "2", weight: "bold" },
    { id: 2, name: 'Universitário', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 3, name: 'Baile', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 4, name: 'Solteirões', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 5, name: 'Nerd', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 6, name: 'Temática', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 7, name: 'Jogos', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 8, name: 'Música Ao Vivo', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 9, name: 'Zero álcool', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 10, name: 'LOUCURA', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 11, name: 'Na rua', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 12, name: 'Evento', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 13, name: 'Chácara', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 14, name: 'Colegial', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 15, name: 'Standup', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 16, name: 'Sustentável', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 17, name: 'Pop', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
    { id: 18, name: 'Rock', type: 'tag', colorName: 'purpleT2', highlightColor: 'purpleT3', ringColor: 'transparent', ringThickness: "0", },
];
